version: "3.0"

services:

    init-geth:
        image: ethereum/client-go:latest
        container_name: geth-init
        env_file: .env
        volumes:
            - ./geth-data:/execution_data
            - ./configs:/configs
        command: >
            --datadir=/execution_data init ./configs/genesis.json

    geth:
        image: ethereum/client-go:latest
        container_name: geth
        depends_on:
            - init-geth
        entrypoint: /bin/sh
        volumes:
            - ./geth-data:/root/.ethereum
            - ${GETH_ANCIENT_CHAINDATA_DIR}:/root/ancient-data
            - ./scripts:/root/scripts:ro
            - ./jwttoken:/root/jwttoken:rwo
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        expose:
            - 8551
        env_file: .env
        command: /root/scripts/start-geth.sh
        restart: on-failure
        stop_grace_period: 3m

    beacon_node:
        image: sigp/lighthouse:latest
        container_name: beacon
        volumes:
            - ./lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./jwttoken:/root/jwttoken:ro
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        restart: on-failure
        stop_grace_period: 3m

    validator_client:
        image: sigp/lighthouse:latest
        volumes:
            - ./lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./validator_keys:/root/validator_keys:ro
        depends_on:
            - beacon_node
        ports:
            - 5064:5064/tcp     # metrics endpoint
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        restart: on-failure
        stop_grace_period: 3m
